from PyQt6.QtCore import QTranslator, Qt
import re

class LanguageManager:
    UI_TRANSLATIONS = {
        "ar": {
            "File": "ملف",
            "Edit": "تحرير",
            "View": "عرض",
            "Tools": "أدوات",
            "Settings": "الإعدادات",
            "Help": "مساعدة",
            "Data Grid": "جدول البيانات",
            "Map": "الخريطة",
            "Range comparison": "مقارنة المدى",
            "Select weapons and add them to the map. Only range rings are shown.": "اختر أسلحة وأضفها للخريطة. تُعرض حلقات المدى فقط.",
            "Search weapons…": "بحث في الأسلحة…",
            "Add to map": "إضافة للخريطة",
            "Click to place": "انقر للوضع",
            "Click map…": "انقر على الخريطة…",
            "Fit all": "ملاءمة الكل",
            "On map": "على الخريطة",
            "{n} weapons on map": "{n} سلاح على الخريطة",
            "Select a weapon with valid range.": "اختر سلاحاً بمدى صالح.",
            "Map Tool": "أداة الخريطة",
            "Loading map…": "جاري تحميل الخريطة…",
            "Bring forward": "إلى الأمام",
            "Send backward": "إلى الخلف",
            "Map range azimuth": "زوايا مدى الدائرة على الخريطة",
            "Transfer scenario": "سيناريو النقل من المحاكي",
            "Weapon & model": "السلاح والطراز",
            "Guidance type": "نوع التوجيه",
            "Target types": "أنواع الأهداف / التصنيف",
            "Delivery method": "أسلوب الإيصال",
            "Weapon coordinates": "إحداثيات السلاح",
            "Target coordinates": "إحداثيات الهدف",
            "Measured distance": "المسافة المقاسة",
            "Azimuth": "السمت",
            "Launch profile": "ملف الإطلاق",
            "Target location name": "اسم موقع الهدف",
            "Legend": "دليل الرموز",
            "Launch / range": "الإطلاق / حلقة المدى",
            "Target": "الهدف",
            "Path": "مسار المحاكاة",
            "Defense": "الدفاع",
            "Measure": "قياس",
            "Copy coordinates": "نسخ الإحداثيات",
            "Low (faster TOF)": "منخفض (زمن وصول أسرع)",
            "High (slower)": "مرتفع (أبطأ)",
            "Ballistic": "بالستي",
            "Cruise": "انتحائي",
            "Direct": "مباشر",
            "Single Weapon View": "عرض السلاح الفردي",
            "Control Panel": "لوحة التحكم",
            "Favorites": "المفضلة",
            "Favorites dashboard": "لوحة المفضلة",
            "Search favorites...": "البحث في المفضلة...",
            "Favorite (Favorites tab)": "مفضل (تبويب المفضلة)",
            "Sort: Name A→Z": "ترتيب: الاسم أ→ي",
            "Sort: Name Z→A": "ترتيب: الاسم ي→أ",
            "Sort: Range ↑": "ترتيب: المدى تصاعدي",
            "Sort: Range ↓": "ترتيب: المدى تنازلي",
            "Sort: Category A→Z": "ترتيب: الفئة أ→ي",
            "Sort: Category Z→A": "ترتيب: الفئة ي→أ",
            "Min km": "من كم",
            "Max km": "إلى كم",
            "Language": "اللغة",
            "English": "الإنجليزية",
            "Arabic": "العربية",
            "Theme": "السمة",
            "Dark": "داكن",
            "Light": "فاتح",
            "Orange Black": "برتقالي وأسود",
            "Cyber Neon": "نيون سيبراني",
            "Dark (Carto)": "داكن (Carto)",
            "Satellite (Esri)": "قمر صناعي (Esri)",
            "OpenStreetMap": "خريطة الشوارع المفتوحة",
            "OpenTopoMap": "خريطة طبوغرافية مفتوحة",
            "Preferences": "التفضيلات",
            "Cancel": "إلغاء",
            "OK": "موافق",
            "Backup saved to:": "تم حفظ النسخة الاحتياطية في:",
            "Add multiple images to gallery": "إضافة عدة صور إلى المعرض",
            "Browse multiple images…": "استعراض عدة صور…",
            "Re-stage existing models": "إعادة تجهيز النماذج الحالية",
            "Selected weapon:": "السلاح المحدد:",
            "Unknown": "غير معروف",
            "General": "عام",
            "Map": "الخريطة",
            "Map tile mode": "وضع بلاطات الخريطة",
            "Offline (local tiles only)": "بدون إنترنت (بلاطات محلية فقط)",
            "Online (download when needed)": "متصل (تحميل عند الحاجة)",
            "Auto (cache first, then online)": "تلقائي (كاش أولاً ثم متصل)",
            "Default basemap": "نوع الخريطة الافتراضي",
            "Default Latitude": "خط العرض الافتراضي",
            "Default Longitude": "خط الطول الافتراضي",
            "Basemap": "نوع الخريطة",
            "Status": "الحالة",
            "Download": "تحميل",
            "Not downloaded": "غير محمّل",
            "tiles": "بلاطة",
            "Download all basemaps (4 types)": "تحميل كل أنواع الخريطة (4)",
            "Download world overview (Z0–5, all basemaps)": "تحميل العالم — طبقات 0–5 (كل الأنواع)",
            "Download world overview": "تحميل نظرة العالم",
            "Downloads all world tiles at zoom levels 0–5 for every basemap type (~60–100 MB).": "يحمّل كل بلاطات العالم للطبقات 0–5 لجميع أنواع الخرائط (~60–100 MB).",
            "Download all world map tiles for zoom levels 0–5\nfor all four basemap types (Dark, Satellite, OSM, Topo)?\n\nApproximate size: 60–100 MB.": "تحميل كل بلاطات العالم للطبقات 0–5\nلجميع أنواع الخرائط الأربعة (داكن، قمر صناعي، OSM، Topo)؟\n\nالحجم التقريبي: 60–100 MB.",
            "Refresh cache status": "تحديث حالة الكاش",
            "Font color": "لون الخط",
            "Company branding": "هوية الشركة",
            "Files & media": "الملفات والوسائط",
            "Offline .gmdb maps folder": "مجلد خرائط .gmdb بدون إنترنت",
            "Browse .gmdb folder": "استعراض مجلد .gmdb",
            "2D gallery preview extensions (comma-separated)": "امتدادات معاينة المعرض ثنائي الأبعاد (مفصولة بفاصلة)",
            "Local AI (Ollama)": "ذكاء اصطناعي محلي (Ollama)",
            "Enable local AI (Ollama)": "تفعيل الذكاء الاصطناعي المحلي (Ollama)",
            "Database": "قاعدة البيانات",
            "Backup Database": "نسخ احتياطي لقاعدة البيانات",
            "Import SQLite Database": "استيراد قاعدة SQLite",
            "Export Database": "تصدير قاعدة البيانات",
            "This basemap is not downloaded yet. Download it from Settings → Map or switch to Online/Auto mode.": "نوع الخريطة هذا غير محمّل بعد. حمّله من الإعدادات → الخريطة أو غيّر الوضع إلى متصل/تلقائي.",
            "Maps always use locally cached tiles (offline mode).": "الخرائط تستخدم دائماً البلاطات المحلية (وضع بدون إنترنت).",
            "Browse PNG": "استعراض PNG",
            "Show/hide input tools": "إظهار/إخفاء أدوات الإدخال",
            ".png  .jpg  .jpeg  .webp": ".png  .jpg  .jpeg  .webp",
            ".obj  .stl  .glb  .gltf  .fbx  .dae": ".obj  .stl  .glb  .gltf  .fbx  .dae",
            "Startup tab": "تبويب بدء التشغيل",
            "Weapon Control (default)": "التحكم بالسلاح (افتراضي)",
            "Last opened tab": "آخر تبويب مفتوح",
            "Company name": "اسم الشركة",
            "Company logo size": "حجم شعار الشركة",
            "Company logo width": "عرض شعار الشركة",
            "Company logo height": "ارتفاع شعار الشركة",
            "Company logo scale": "مقياس شعار الشركة",
            "Company logo": "شعار الشركة",
            "Browse company logo": "استعراض شعار الشركة",
            "Select company logo": "اختر شعار الشركة",
            "Font Size": "حجم الخط",
            "Apply": "تطبيق",
            "Apply Settings": "تطبيق الإعدادات",
            "Filter": "تصفية",
            "Reset": "إعادة تعيين",
            "Search": "بحث",
            "Search cards...": "البحث في البطاقات...",
            "Search model, name, manufacturer...": "ابحث في الطراز والاسم والمصنع...",
            "Category": "الفئة",
            "Country": "الدولة",
            "No filters": "بدون مرشحات",
            "All Categories": "كل الفئات",
            "All Countries": "كل الدول",
            "Min range km": "المدى الأدنى كم",
            "Max range km": "المدى الأقصى كم",
            "Choose Font Color": "اختر لون الخط",
            "Settings applied.": "تم تطبيق الإعدادات.",
            "Settings Applied": "تم تطبيق الإعدادات",
            "Changes applied successfully.": "تم تطبيق التغييرات بنجاح.",
            "Show Weapon on Map": "إظهار السلاح على الخريطة",
            "Select a weapon to view details": "اختر سلاحا لعرض التفاصيل",
            "Gallery: no images": "المعرض: لا توجد صور",
            "Selected weapon: none": "السلاح المحدد: لا يوجد",
            "Set as dashboard thumbnail (primary)": "تعيين كصورة مصغرة رئيسية",
            "Add Image to Weapon Gallery": "إضافة صورة إلى معرض السلاح",
            "Browse PNG": "استعراض PNG",
            "Select PNG thumbnail": "اختر صورة PNG مصغرة",
            "PNG path for gallery / thumbnail": "مسار PNG للمعرض / الصورة المصغرة",
            "Map Zoom +": "تكبير الخريطة +",
            "Map Zoom -": "تصغير الخريطة -",
            "Prev Image": "الصورة السابقة",
            "Next Image": "الصورة التالية",
            "No image": "لا توجد صورة",
            "No gallery images": "لا توجد صور في المعرض",
            "Image not found": "الصورة غير موجودة",
            "Center Map": "توسيط الخريطة",
            "Draw Range": "رسم المدى",
            "Zoom +": "تكبير +",
            "Zoom -": "تصغير -",
            "Export map as PNG": "تصدير الخريطة كـ PNG",
            "PNG images (*.png);;All files (*.*)": "صور PNG (*.png);;كل الملفات (*.*)",
            "Export failed": "فشل التصدير",
            "Could not save the map image.": "تعذّر حفظ صورة الخريطة.",
            "Map Tools": "أدوات الخريطة",
            "Specification": "المواصفة",
            "Value": "القيمة",
            "Gallery": "المعرض",
            "Gallery tools": "أدوات المعرض",
            "Gallery/Thumbnail PNG File Path": "مسار ملف PNG للمعرض/الصورة المصغرة",
            "3D Model Path": "مسار النموذج ثلاثي الأبعاد",
            "3D model path (.obj, .stl, .ply, .fbx, .dae, .glb, .gltf, .usdz)": "مسار نموذج ثلاثي الأبعاد (.obj, .stl, .ply, .fbx, .dae, .glb, .gltf, .usdz)",
            "Set as primary 3D model": "تعيين كنموذج ثلاثي الأبعاد رئيسي",
            "Browse 3D Model": "استعراض نموذج ثلاثي الأبعاد",
            "Add 3D model to selected weapon": "إضافة نموذج ثلاثي الأبعاد للسلاح المحدد",
            "Select 3D model": "اختر نموذج ثلاثي الأبعاد",
            "3D Models (*.obj *.stl *.ply *.fbx *.dae *.glb *.gltf *.usdz);;All files (*.*)": "نماذج ثلاثية الأبعاد (*.obj *.stl *.ply *.fbx *.dae *.glb *.gltf *.usdz);;كل الملفات (*.*)",
            "Please select a valid 3D model file.": "يرجى اختيار ملف نموذج ثلاثي الأبعاد صالح.",
            "Failed to save model.": "فشل حفظ النموذج.",
            "3D model saved successfully.": "تم حفظ النموذج ثلاثي الأبعاد بنجاح.",
            "3D model converted to GLB and saved successfully.": "تم تحويل النموذج إلى GLB وحفظه بنجاح.",
            "Converter dependency missing; saving original model format.": "مكوّن التحويل غير متوفر؛ سيتم حفظ النموذج بصيغته الأصلية.",
            "Auto-convert failed; saving original model format.": "فشل التحويل التلقائي؛ سيتم حفظ النموذج بصيغته الأصلية.",
            "Default Map View": "عرض الخريطة الافتراضي",
            "Full Map Layout": "تخطيط الخريطة الكامل",
            "Hide/Show right pane": "إخفاء/إظهار اللوحة اليمنى",
            "Please select a weapon first.": "يرجى اختيار سلاح أولا.",
            "Please select a valid image file.": "يرجى اختيار ملف صورة صالح.",
            "Failed to save image.": "فشل حفظ الصورة.",
            "Image saved successfully.": "تم حفظ الصورة بنجاح.",
            "Clear": "مسح",
            "Export": "تصدير",
            "Add": "إضافة",
            "Edit": "تعديل",
            "Delete": "حذف",
            "Category -> Missile": "الفئة -> الصاروخ",
            "Range (km)": "المدى (كم)",
            "Speed (Mach)": "السرعة (ماخ)",
            "Warhead Type": "نوع الرأس الحربي",
            "Warhead Weight": "وزن الرأس الحربي",
            "Missile Name": "اسم الصاروخ",
            "Type": "النوع",
            "Length": "الطول",
            "Diameter": "القطر",
            "Weight": "الوزن",
            "Guidance": "التوجيه",
            "Propulsion": "الدفع",
            "Platform": "المنصة",
            "Status": "الحالة",
            "Manufacturer": "المصنع",
            "Introduction Year": "سنة الإدخال",
            "Image Preview": "معاينة الصورة",
            "Reports": "التقارير",
            "Reports workspace": "مساحة التقارير",
            "Report preview": "معاينة التقرير",
            "Report type": "نوع التقرير",
            "Map settings": "إعدادات الخريطة",
            "Document text settings": "إعدادات نص التقرير",
            "Weapons and export tools": "أدوات الأسلحة والتصدير",
            "Map settings (for report map image)": "إعدادات الخريطة (لصورة خريطة التقرير)",
            "Single click to set center point": "نقرة واحدة لتحديد نقطة المركز",
            "Marker: click to set center point": "أداة العلامة: انقر لتحديد نقطة المركز",
            "Hand: drag to move map": "أداة اليد: اسحب لتحريك الخريطة",
            "Drag to move map, click to set center point": "اسحب لتحريك الخريطة، وانقر لتحديد نقطة المركز",
            "Drag to browse map, then click to set point": "اسحب لتصفح الخريطة ثم انقر لتحديد النقطة",
            "Reset to default center": "إعادة التعيين إلى المركز الافتراضي",
            "Include title": "تضمين العنوان",
            "Include introduction": "تضمين المقدمة",
            "Include specifications": "تضمين المواصفات",
            "Include gallery images": "تضمين صور المعرض",
            "Include closing notes": "تضمين ملاحظات الختام",
            "Document title (optional)": "عنوان المستند (اختياري)",
            "Introduction / cover text (optional)": "مقدمة / نص الغلاف (اختياري)",
            "Closing / appendix notes (optional)": "ملاحظات الختام / الملحق (اختياري)",
            "File format": "صيغة الملف",
            "Weapons (for individual / comparison)": "الأسلحة (للتقرير الفردي / المقارنة)",
            "Records": "عدد السجلات",
            "Specifications": "المواصفات",
            "Field": "الحقل",
            "Value": "القيمة",
            "No images on file.": "لا توجد صور محفوظة.",
            "Range / effects diagram": "مخطط المدى والتأثيرات",
            "Included in export: real map snapshot with effects overlays.": "يتم تضمين لقطة خريطة حقيقية مع طبقات التأثيرات في التصدير.",
            "Backup Database": "نسخ احتياطي لقاعدة البيانات",
            "Import SQLite Database": "استيراد قاعدة SQLite",
            "Export Database": "تصدير قاعدة البيانات",
            "Backup Complete": "اكتمل النسخ الاحتياطي",
            "Backup Failed": "فشل النسخ الاحتياطي",
            "Import Complete": "اكتمل الاستيراد",
            "Import Failed": "فشل الاستيراد",
            "Export Complete": "اكتمل التصدير",
            "Export Failed": "فشل التصدير",
            "Confirm Import": "تأكيد الاستيراد",
            "This will replace current local data with selected database.\nContinue?": "سيؤدي هذا إلى استبدال البيانات المحلية الحالية بقاعدة البيانات المحددة.\nهل تريد المتابعة؟",
            "Please reopen the app to ensure all views refresh.": "يرجى إعادة فتح التطبيق لضمان تحديث جميع الواجهات.",
            "Spec Fields": "حقول المواصفات",
            "Open weapon folder": "فتح مجلد السلاح",
            "Open media folder (images & models) in File Explorer": "فتح مجلد الوسائط (الصور والنماذج) في مستكشف الملفات",
            "Load a weapon first.": "حمّل سلاحًا أولًا.",
            "Could not open folder. Path:\n": "تعذر فتح المجلد. المسار:\n",
            "Select specification fields": "اختيار حقول المواصفات",
            "Browse .gmdb folder": "تصفح مجلد خرائط .gmdb",
            "Offline .gmdb maps folder": "مجلد خرائط .gmdb دون اتصال",
            "Select .gmdb maps folder": "اختر مجلد خرائط .gmdb",
            "Specifications fields (single view + comparison reports)": "حقول المواصفات (العرض الفردي + تقارير المقارنة)",
            "2D gallery preview extensions (comma-separated)": "امتدادات معاينة معرض 2D (مفصولة بفواصل)",
            "SWOT Analysis": "تحليل SWOT",
            "Simulator": "المحاكي",
            "Enable local AI (Ollama) in Preferences first.": "فعّل الذكاء المحلي (Ollama) من التفضيلات أولاً.",
            "Enable local AI (Ollama)": "تفعيل الذكاء المحلي (Ollama)",
            "Ollama URL": "رابط Ollama",
            "Ollama model": "نموذج Ollama",
            "SWOT / analysis tip: Prefer instruction-tuned models (presets listed first).\nExamples: llama3.3:70b-instruct-q4_K_M or qwen2.5:32b-instruct for accuracy and numbered structure; for Arabic-heavy UI, qwen2.5:14b/32b-instruct often behaves well.\nUse temperature ~0.2-0.4 for analytical drafts. Install with: ollama pull <tag>":
                "نصائح تحليل / SWOT: فضّل نماذج «instruction‑tuned» (القوائم المقترحة في الأعلى).\nأمثلة: llama3.3:70b-instruct-q4_K_M أو qwen2.5:32b-instruct للدقة والهيكلة المرقمة؛ لواجهة عربية كثيرة قد تناسبك qwen2.5:14b/32b-instruct غالبًا.\nدرجة الحرارة ~0.2-0.4 تقلل الحشو الزائد. تنصيب: ollama pull ثم اسم الوسم",
            "AI temperature": "حرارة النموذج",
            "AI timeout": "مهلة الذكاء",
            "AI": "الذكاء",
            "AI Generate Notes": "توليد ملاحظات بالذكاء",
            "Save Notes": "حفظ الملاحظات",
            "Notes": "الملاحظات",
            "Notes saved.": "تم حفظ الملاحظات.",
            "Failed to save notes.": "فشل حفظ الملاحظات.",
            "AI notes generation failed.": "فشل توليد الملاحظات بالذكاء.",
            "Status: generating AI draft…": "الحالة: يتم توليد مسودة بالذكاء…",
            "AI draft failed. Falling back to offline draft.": "فشل إنشاء المسودة بالذكاء. سيتم الرجوع لمسودة دون اتصال.",
            "AI Simulator Analysis": "تحليل المحاكي بالذكاء",
            "AI simulator assessment": "تقييم المحاكي بالذكاء",
            "AI bridge unavailable.": "جسر الذكاء غير متاح.",
            "Working…": "جارٍ العمل…",
            "AI Draft Intro": "مسودة مقدمة بالذكاء",
            "AI Executive Summary": "ملخص تنفيذي بالذكاء",
            "AI Draft Closing": "مسودة خاتمة بالذكاء",
            "AI drafting failed: ": "فشل إنشاء النص بالذكاء: ",
            "sim_title": "محاكي المدى التكتيكي",
            "sim_subtitle": "اختر سلاحًا، حدد الهدف على الخريطة، وشغّل معاينة المسار.",
            "sim_style_summary": "طبقات الخريطة والألوان",
            "sim_style_range_ring": "حلقة المدى (قرص الاشتباك)",
            "sim_style_fill_op": "شفافية التعبئة",
            "sim_style_fill_color": "لون التعبئة",
            "sim_style_outline_op": "شفافية المحيط",
            "sim_style_outline_color": "لون المحيط",
            "sim_style_path_group": "خط مسار الطيران",
            "sim_style_path_op": "شفافية الخط",
            "sim_style_path_color": "لون الخط",
            "sim_style_path_weight": "سمك الخط",
            "sim_style_path_dash": "نمط الخط",
            "sim_style_px": "بكسل",
            "sim_path_dash_solid": "متصل",
            "sim_path_dash_short": "شرطات",
            "sim_path_dash_long": "شرطات طويلة",
            "sim_path_dash_dots": "نقاط دائرية",
            "sim_style_reset": "استعادة الافتراضي",
            "sim_weapon_system": "منظومة السلاح",
            "sim_search_label": "بحث",
            "sim_quick_zoom": "تكبير سريع",
            "sim_search_ph": "بحث في القائمة…",
            "sim_select_weapon": "— اختر سلاحًا —",
            "sim_labels_on": "التسميات ✓",
            "sim_labels_off": "التسميات",
            "sim_play": "▶ تشغيل",
            "sim_basemap": "الخريطة الأساسية",
            "sim_bm_dark": "داكنة",
            "sim_bm_street": "شوارع",
            "sim_bm_satellite": "قمر صناعي",
            "sim_snap_range": "التصاق الهدف بالمدى",
            "sim_measure": "قياس المسافة",
            "sim_measure_hint": "قياس: انقر نقطتين (Esc للإلغاء)",
            "sim_export_png": "تصدير صورة",
            "sim_open_main_map": "فتح في الخريطة الرئيسية",
            "sim_transfer_main_map": "إرسال المشهد إلى الخريطة الرئيسية",
            "sim_fullscreen_enter": "ملء الشاشة",
            "sim_fullscreen_exit": "الخروج من ملء الشاشة",
            "sim_sidebar_hide_menu": "إخفاء قائمة المحاكي",
            "sim_sidebar_show_menu": "إظهار قائمة المحاكي",
            "sim_tools_summary": "أدوات المحاكي",
            "sim_swot_toggle": "SWOT",
            "sim_save_session": "حفظ",
            "sim_load_session": "تحميل",
            "sim_export_system": "تصدير",
            "sim_components": "مكونات الخريطة",
            "sim_comp_range_azimuth": "زوايا مدى الدائرة",
            "sim_comp_legend": "الدليل",
            "sim_comp_hud": "لوحة المعلومات",
            "sim_comp_status": "شريط المسافة",
            "sim_comp_telemetry": "القياسات",
            "sim_comp_title": "عنوان الصاروخ",
            "sim_comp_zoom": "أزرار التكبير",
            "sim_comp_help": "المساعدة",
            "sim_comp_ai": "تحليل الذكاء",
            "sim_comp_swot": "SWOT",
            "sim_comp_model3d": "نموذج 3D",
            "sim_layout_drag_panel": "نقل اللوحة",
            "sim_swot_panel_glass": "SWOT · خلفيات لوحات الخريطة",
            "sim_layout_glass_op": "شفافية الزجاج",
            "sim_swot_title": "SWOT",
            "sim_swot_net": "الصافي",
            "sim_swot_weighted": "موزون",
            "sim_swot_updated": "آخر تحديث",
            "sim_reset_target": "إعادة الهدف",
            "sim_undo_launch": "تراجع عن الإطلاق",
            "sim_defense_layer": "طبقة دفاع افتراضية",
            "sim_high_contrast": "تباين عالٍ",
            "sim_flight_profile": "ملف الطيران",
            "sim_profile_low": "منخفض (زمن أقصر)",
            "sim_profile_high": "مرتفع (زمن أطول)",
            "sim_arc_style": "نمط القوس",
            "sim_arc_ballistic": "بالستي",
            "sim_arc_cruise": "انتحائي",
            "sim_arc_direct": "مباشر",
            "sim_play_speed": "سرعة التشغيل",
            "sim_load_full_catalog": "تحميل كامل القائمة",
            "sim_legend_title": "دليل الرموز",
            "sim_legend_launch": "الإطلاق / حلقة المدى",
            "sim_legend_target": "الهدف",
            "sim_legend_path": "مسار المحاكاة",
            "sim_ctx_copy_coords": "نسخ الإحداثيات",
            "sim_ctx_copied_coords": "تم نسخ الإحداثيات",
            "sim_stats": "محاكاة",
            "sim_map_hint": "الخريطة: نقرة = هدف · السحب = تحريك · علامات الإطلاق/الهدف قابلة للسحب.",
            "sim_tutorial_welcome": "مرحبًا",
            "sim_tutorial_intro": "جولة سريعة: اختر سلاحًا، انقر الخريطة لوضع الهدف داخل حلقة المدى، ثم اضغط تشغيل لمعاينة مسار بسيط.",
            "sim_tutorial_next": "التالي",
            "sim_tutorial_skip": "تخطي",
            "sim_tutorial_done": "ابدأ",
            "sim_tutorial_step1": "اختر سلاحًا من القائمة أو من التطبيق الرئيسي.",
            "sim_tutorial_step2": "انقر الخريطة لوضع الهدف؛ اسحب العلامات لضبط الإطلاق والهدف.",
            "sim_tutorial_step3": "استخدم تشغيل لمعاينة المسار؛ مفاتيح: مسافة = تشغيل، Z = تراجع، R = إعادة الهدف، M = قياس.",
            "sim_help_title": "اختصارات",
            "sim_help_keys": "مسافة: تشغيل · +/-: تكبير · Z: تراجع موقع الإطلاق · R: إعادة الهدف · M: قياس · ؟: هذه اللوحة",
            "sim_status_no_weapon": "لا يوجد سلاح محمّل",
            "sim_hud_range": "المدى",
            "sim_hud_launch": "الإطلاق",
            "sim_dist": "المسافة",
            "sim_tof_est": "زمن تقريبي",
            "sim_inside_range": "داخل المدى",
            "sim_outside_range": "خارج المدى",
            "sim_export_busy": "جارٍ التصدير…",
            "sim_export_fail": "فشل التصدير",
            "sim_export_ok": "اكتمل التصدير",
            "sim_zoom": "تكبير",
            "sim_neon_readiness": "الاستعداد",
            "sim_neon_time": "الزمن",
            "sim_neon_speed": "السرعة",
            "sim_neon_dist": "المسافة",
            "sim_neon_position": "الإحداثيات",
            "sim_neon_standby": "استعداد — بانتظار الإطلاق",
            "sim_neon_los": "خط الرؤية",
            "sim_neon_ready": "جاهز",
            "sim_neon_tof_preview": "زمن الطيران التقديري",
            "sim_neon_nominal": "اسمي",
            "sim_neon_armed": "جاهز للإطلاق",
            "sim_neon_tminus": "T−",
            "sim_neon_liftoff": "إقلاع",
            "sim_neon_in_flight": "في الطيران",
            "sim_neon_elapsed": "منقضٍ",
            "sim_neon_track": "المسار",
            "sim_neon_terminal": "نهائي",
            "sim_neon_mission": "مهمة",
            "sim_model_no_file": "لا يوجد نموذج ثلاثي الأبعاد للسلاح المحدد.",
            "sim_model_load_failed": "تعذر تحميل النموذج ثلاثي الأبعاد داخل المحاكي.",
            "Status: select a weapon to start.": "الحالة: اختر سلاحًا للبدء.",
            "No weapon selected": "لا يوجد سلاح محدد",
            "Compare with weapon...": "قارن مع سلاح...",
            "Compare": "مقارنة",
            "Analysis Context": "سياق التحليل",
            "Analyst": "المحلل",
            "Scenario / Theater": "السيناريو / المسرح",
            "Scenario / theater": "السيناريو / المسرح",
            "Map context: n/a": "سياق الخريطة: غير متاح",
            "Save Version": "حفظ نسخة",
            "Load Latest": "تحميل الأحدث",
            "Overview": "نظرة عامة",
            "Strengths": "نقاط القوة",
            "Weaknesses": "نقاط الضعف",
            "Opportunities": "الفرص",
            "Threats": "التهديدات",
            "Recommendations": "التوصيات",
            "Recommendations and mitigations...": "التوصيات وخطط التخفيف...",
            "AI-assisted Draft": "مسودة بمساعدة الذكاء الاصطناعي",
            "Clear Draft": "مسح المسودة",
            "SWOT Editor": "محرر SWOT",
            "Quadrant": "الربع",
            "Impact": "التأثير",
            "Confidence": "الثقة",
            "Live score preview: n/a": "معاينة النتيجة المباشرة: غير متاح",
            "Scoring": "التقييم",
            "Current weapon": "السلاح الحالي",
            "Comparison weapon": "سلاح المقارنة",
            "Compare legend: green=shared, red=only current, blue=only comparison.": "دليل المقارنة: الأخضر=مشترك، الأحمر=للحالي فقط، الأزرق=للمقارنة فقط.",
            "History": "السجل",
            "Trend: n/a": "الاتجاه: غير متاح",
            "One item per line: Strengths": "عنصر واحد في كل سطر: نقاط القوة",
            "One item per line: Weaknesses": "عنصر واحد في كل سطر: نقاط الضعف",
            "One item per line: Opportunities": "عنصر واحد في كل سطر: الفرص",
            "One item per line: Threats": "عنصر واحد في كل سطر: التهديدات",
            "Status: weapon selected. Fill SWOT, then save and compare.": "الحالة: تم اختيار السلاح. أكمل SWOT ثم احفظ وقارن.",
            "Live score preview: raw net {summary.get('net_score', 0):+}, weighted net {float(summary.get('weighted_net_score', 0.0)):+.2f}.": "معاينة النتيجة المباشرة: الصافي الخام {summary.get('net_score', 0):+}، والصافي الموزون {float(summary.get('weighted_net_score', 0.0)):+.2f}.",
            "SWOT": "SWOT",
            "Please select a weapon first.": "يرجى اختيار سلاح أولاً.",
            "Failed to save SWOT report.": "فشل حفظ تقرير SWOT.",
            "Status: SWOT version saved.": "الحالة: تم حفظ نسخة SWOT.",
            "Saved SWOT version.": "تم حفظ نسخة SWOT.",
            "Status: latest SWOT loaded.": "الحالة: تم تحميل أحدث SWOT.",
            "Status: no saved SWOT yet.": "الحالة: لا يوجد SWOT محفوظ بعد.",
            "Trend: need at least 2 saved versions.": "الاتجاه: يلزم وجود نسختين محفوظتين على الأقل.",
            "Current weapon": "السلاح الحالي",
            "Comparison weapon": "سلاح المقارنة",
            "Status: historical version loaded.": "الحالة: تم تحميل نسخة تاريخية.",
            "Please select a base weapon first.": "يرجى اختيار سلاح أساسي أولاً.",
            "Status: compare view updated.": "الحالة: تم تحديث عرض المقارنة.",
            "Status: AI-assisted draft generated.": "الحالة: تم إنشاء مسودة بمساعدة الذكاء الاصطناعي.",
            " (offline)": " (دون اتصال)",
            "Treat this profile as adversary ordinance; baseline defensive doctrine is a strength if exercised.": "اعتبر هذا الملف تهديدًا معادًا؛ إن أسس العقيدة الدفاعية عند تنفيذها تُعد نقطة قوة.",
            "Threat package unknowns (seeker EMI, doctrine, stocks) widen defender planning risk ({platform}).": "المجهولات حول الباقة الهجومية (الحرب الإلكترونية للباحث، العقيدة، الذخائر) تعزز مخاطر تخطيط المدافع ({platform}).",
            "Adversary may employ {guidance} seeker envelopes the defender must model in EW and EMCON.": "قد يستخدم الخصم أغوار باحث {guidance} يجب على المدافع ضبط نمذجته في الحرب الإلكترونية وضبط الإشعارات.",
            "Stand-off reach (~{rk} km) holds defender depth and repositioning timelines at risk.": "المدى البرّي (~{rk} كم) يعرّض عمق المدافع وجداول إعادة الانتشار للخطر.",
            "Compressed warning/engagement timelines if ISR gaps exist against distant launches.": "تضاغط زمن التحذير/الاشتباك عند وجود فجوات في الاستطلاع والمراقبة مقابل الإطلاقات البعيدة.",
            "Passive sensing, dispersion, deception, and counter-fire on launch architecture can blunt long-range raids.": "الاستشعار الخامل والتشتيت والخداع والنيران المرتدة على بنية الإطلاق قد تصعِّب غارات بعيدة المدى.",
            "Engagement footprint (~{rk} km) constrains defender movement and bastion layouts.": "بصمة الاشتباك (~{rk} كم) تقيد تحرك المدافع وتخطيط الحصون.",
            "High-speed kinematics (~{sp} Mach) shorten defender intercept windows.": "الحركيات عالية السرعة (~{sp} ماخ) تقصر نوافذ الاعتراض لدى المدافع.",
            "Layered shooters, cueing relays, and pre-briefed fire baskets can reclaim engagement time.": "الطبقات المطلقة للنار، شبكات الإسناد الذكي والسلال النارية الموافق عليها مسبقًا قد تستعيد زمن الاشتباك.",
            "Threat speed (~{sp} Mach) still shapes defender geometry and interceptor selection.": "سرعة التهديد (~{sp} ماخ) لا تزال تشكل الهندسة المعمارية الدفاعية واختيار المعترضات.",
            "Heavy warhead mass (~{wh} kg) raises consequences of leakers against defender assets.": "كتلة الرأس الكبيرة (~{wh} كغ) ترفع ضرورة التصدي لالتسربات تجاه موارد المدافع.",
            "Even moderate warheads (~{wh} kg) demand hardening or dispersal for defended assets.": "حتى الرءوس المتوسطة (~{wh} كغ) تقتضي تصليبًا أو توزيعًا للموارد المحمية.",
            "Operational adversary inventories imply repeatable, exercised threat against the defender.": "مخزون الخصم العامل يشير إلى تهديد متكرّر ومدرّب ضدّ المدافع.",
            "Declared status '{status}' may reduce near-term readiness—monitor reactivation timelines.": "الحالة المعلنة '{status}' قد تقلل الجاهزية قصيرة الأجل؛ راقبوا جداول إعادة التنشيط.",
            "Older seeker/front-end generations may yield exploitable EW and signature gaps for today's defender toolkit.": "قد تتيح الأجيال الأقدم من الواجهة/الباحث فجوات في الحرب الإلكترونية والبصمة يمكن لمخزون أدوات الجانب الدفاعي الحديث أن يستثمرها.",
            "Low-altitude cruise routing stresses radar horizons and mutual support for the defender.": "مسار الكروز المنخفض يضغط أفق الرادارات والمساندة المتبادلة للمدافع.",
            "Integrated air picture with low-level gap-fill sensors is a doctrinal strength when funded.": "الصورة الجوية الموحدة مع حساسات تعبئة الفجوات منخفضة الارتفاع قوّة عقائدية عند توفر التمويل.",
            "Barrier CAP, SAM belts on approach axes, and shoot-look-shoot doctrines counter cruise threats.": "إسناد جوي اعتراضي مانع وحزام دفاعات جوية على محاور الاقتراب وعقيدة الإطلاق المرتد «أطلق‑راقب‑أطلق» تقاوِم تهديد الكروز.",
            "Top-attack/heavy ATGW profiles endanger defended armor concentrations if LOS is conceded.": "الصواريخ الموجهة مضادة للدروع الثقيلة أو ضرب‑العلوي تهدّد تجمعات الدروع المحمية إذا تخلّى الجانب الدفاعي عن خط الرؤية.",
            "Terrain masking, concealment discipline, overwatch UAVs, and quick smoke can favor the defender.": "الإخفاء التضاريسي، وانضباط التمويه، والمسيّرات للمراقبة، والدخان السريع تفيد المدافع.",
            "Active protection, hard-kill interceptors at short range, and dismounted overwatch degrade ATGM lethality.": "الحماية النشطة للمركبات والاعتراض الفتاك قصير المدى والمراقبة الراجلة تقلل فاعلية الصواريخ الموجهة مضادة للدروع.",
            "Contestable airspace and long burn AAMs pressure defender fighters and AEW arcs.": "الأجواء المتنازعة وصواريخ جو‑جو طويلة الاحتراق تُضايِق مناورة المقاتلات وخطط عمل طيران الإنذار المبكر الجوي.",
            "Electronic attack, kinematic defeats, staggered shooters, and chaff/expendables counter AAM kinematics.": "الهجوم الإلكتروني والهزيمة الحركية والطبقات المطلقة المتدرجة ومواد تشويش/مستهلكات تقاوم حركيات صواريخ جو‑جو.",
            "Sea/littoral shooters may deny maritime maneuver if coastal ISR is asymmetric.": "البطاريات البحرية أو الساحلية قد تُقيِّد المناورة البحرية عند اعتماد استطلاع ساحلي غير متكافئ.",
            "Doctrine and readiness drift are defender weaknesses unrelated to specs—scenario dependent.": "انحراف العقيدة والجاهزية نقاط ضعف للمدافع لا علاقة لها بالمواصفات—بحسب السيناريو.",
            "Classify adversary seeker or guidance mode implied by stored fields and rehearse EW, decoys, and emissions control tailored to that class.": "صِف وضع توجيه العدو الظاهر من الحقول المخزّنة، ودرِّب الحرب الإلكترونية والخديعة وضبط الانبعاثات وفق ذلك الصنف.",
            "Tighten layered detection-to-engagement handoffs—no single sensor or shooter may carry the intercept alone.": "قوّ سلاسل انتقال الاكتشاف إلى الاشتباك طبقيًا بحيث لا تقع مهمة الاعتراض على مستشعر أو منصّة واحدة وحدهما.",
            "Rehearse passive cueing and dispersal timelines so salvos cannot collapse defender depth in one strike.": "درّب الإسناد اللاعنيف وجداول التشتيت حتى لا يُسحق العمق الدفاعي أمام زخّة مدمرة واحدة.",
            "Table high-value defended assets vs. credible leaker scenarios and allocate hardening or relocation first.": "اعرض الأصول المحمية عالية القيمة مقابل حالات تهريب واقعية وخصّص التصليب أو الإعادة نشر أولًا.",
            "Exercise logistics and reload under repeated fires; stale magazines nullify technically sound defenses.": "ادرِب خطوط الإمداد والإعادة التعبئة تحت متتاليات؛ المخازن المتعطّلة تُبطّل خططًا سليمة ظاهريًا.",
            "Live score preview": "معاينة النتيجة المباشرة",
            "Raw net": "الصافي الخام",
            "Weighted net": "الصافي الموزون",
            "Trend": "الاتجاه",
            "Raw": "خام",
            "Weighted": "موزون",
            "across": "عبر",
            "versions": "نسخ",
            "Map context": "سياق الخريطة",
            "n/a": "غير متاح",
        }
    }
    DATA_TRANSLATIONS = {
        "ar": {
            "Cruise Missile": "صاروخ كروز",
            "Air-to-Air Missile (AAM)": "صاروخ جو-جو",
            "Air-to-Surface Missile (ASM)": "صاروخ جو-سطح",
            "Anti-Tank Guided Missile (ATGM)": "صاروخ موجه مضاد للدروع",
            "United States": "الولايات المتحدة",
            "Russia": "روسيا",
            "China": "الصين",
            "France": "فرنسا",
            "United Kingdom": "المملكة المتحدة",
            "Germany": "ألمانيا",
            "Israel": "إسرائيل",
            "Iran": "إيران",
            "Turkey": "تركيا",
            "India": "الهند",
            "Operational": "عامل",
            "Retired": "متقاعد",
            "Prototype": "نموذج أولي",
            "Active": "نشط",
            "Inactive": "غير نشط",
        }
    }
    TOKEN_TRANSLATIONS = {
        "ar": {
            "missile": "صاروخ",
            "rocket": "صاروخ",
            "ballistic": "باليستي",
            "cruise": "كروز",
            "guided": "موجه",
            "unguided": "غير موجه",
            "anti": "مضاد",
            "tank": "دروع",
            "air": "جو",
            "surface": "سطح",
            "ship": "سفينة",
            "naval": "بحري",
            "land": "بري",
            "defense": "دفاع",
            "attack": "هجومي",
            "short": "قصير",
            "medium": "متوسط",
            "long": "بعيد",
            "range": "مدى",
            "strategic": "استراتيجي",
            "tactical": "تكتيكي",
            "launcher": "قاذف",
            "drone": "مسيرة",
            "uav": "طائرة بدون طيار",
            "hypersonic": "فرط صوتي",
            "interceptor": "اعتراضي",
            "defensive": "دفاعي",
            "offensive": "هجومي",
        }
    }
    TECHNICAL_IDIOMS = {
        "gps", "ins", "radar", "laser", "ir", "infrared", "active radar", "semi-active",
        "turbojet", "ramjet", "mach", "fts", "api", "glb", "gltf", "obj", "usdz", "sam", "aam", "asm", "atgm"
    }

    def __init__(self, app):
        self.app = app
        self.translator = QTranslator()
        self.current_code = "en"
        self._country_map = self._build_country_map()

    def load_language(self, lang_name):
        normalized = str(lang_name).strip().lower()
        code = 'ar' if normalized in {'ar', 'arabic'} else 'en'
        qm_file = f"resources/translations/armorygis_{code}.qm"  # Optional, custom fallback is always available.
        loaded = self.translator.load(qm_file)
        if loaded:
            self.app.installTranslator(self.translator)
        self.current_code = code
        if code == 'ar':
            self.app.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        else:
            self.app.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        return True

    def is_arabic(self) -> bool:
        return self.current_code == "ar"

    def tr(self, text: str) -> str:
        if text is None:
            return ""
        if not self.is_arabic():
            return text
        return self.UI_TRANSLATIONS.get("ar", {}).get(text, text)

    def tr_data(self, value):
        if value is None or not self.is_arabic():
            return value
        text = str(value)
        direct = self.DATA_TRANSLATIONS.get("ar", {}).get(text)
        if direct:
            return direct
        country_hit = self._country_map.get(text.lower())
        if country_hit:
            return country_hit
        return self._token_translate(text)

    def untr_data(self, value):
        """Convert translated Arabic display value back to canonical source text."""
        if value is None or not self.is_arabic():
            return value
        text = str(value)
        reverse_direct = {v: k for k, v in self.DATA_TRANSLATIONS.get("ar", {}).items()}
        if text in reverse_direct:
            return reverse_direct[text]
        reverse_country = {v: k.title() for k, v in self._country_map.items()}
        if text in reverse_country:
            return reverse_country[text]
        return value

    def _token_translate(self, text: str) -> str:
        tokens = self.TOKEN_TRANSLATIONS.get("ar", {})
        parts = re.split(r"(\W+)", text)
        translated = []
        for part in parts:
            if self._keep_technical_token(part):
                translated.append(part)
                continue
            key = part.lower()
            translated.append(tokens.get(key, part))
        return "".join(translated)

    def _keep_technical_token(self, token: str) -> bool:
        token = token.strip()
        if not token:
            return True
        lower = token.lower()
        if lower in self.TECHNICAL_IDIOMS:
            return True
        # Preserve model-like codes/abbreviations: AGM-114, AIM120C, Mk48, etc.
        if re.match(r"^[A-Za-z]{1,6}[-_/]?\d+[A-Za-z0-9-_/]*$", token):
            return True
        if token.isupper() and len(token) <= 8:
            return True
        return False

    def _build_country_map(self):
        # Extended country coverage for dynamic DB values.
        return {
            "afghanistan": "أفغانستان",
            "algeria": "الجزائر",
            "argentina": "الأرجنتين",
            "armenia": "أرمينيا",
            "australia": "أستراليا",
            "austria": "النمسا",
            "azerbaijan": "أذربيجان",
            "bahrain": "البحرين",
            "bangladesh": "بنغلاديش",
            "belarus": "بيلاروسيا",
            "belgium": "بلجيكا",
            "brazil": "البرازيل",
            "bulgaria": "بلغاريا",
            "canada": "كندا",
            "chile": "تشيلي",
            "colombia": "كولومبيا",
            "croatia": "كرواتيا",
            "czech republic": "التشيك",
            "denmark": "الدنمارك",
            "egypt": "مصر",
            "estonia": "إستونيا",
            "finland": "فنلندا",
            "georgia": "جورجيا",
            "greece": "اليونان",
            "hungary": "المجر",
            "indonesia": "إندونيسيا",
            "iraq": "العراق",
            "italy": "إيطاليا",
            "japan": "اليابان",
            "jordan": "الأردن",
            "kazakhstan": "كازاخستان",
            "kuwait": "الكويت",
            "lebanon": "لبنان",
            "libya": "ليبيا",
            "malaysia": "ماليزيا",
            "morocco": "المغرب",
            "netherlands": "هولندا",
            "new zealand": "نيوزيلندا",
            "norway": "النرويج",
            "oman": "عمان",
            "pakistan": "باكستان",
            "philippines": "الفلبين",
            "poland": "بولندا",
            "portugal": "البرتغال",
            "qatar": "قطر",
            "romania": "رومانيا",
            "saudi arabia": "السعودية",
            "serbia": "صربيا",
            "singapore": "سنغافورة",
            "slovakia": "سلوفاكيا",
            "south africa": "جنوب أفريقيا",
            "south korea": "كوريا الجنوبية",
            "spain": "إسبانيا",
            "sweden": "السويد",
            "switzerland": "سويسرا",
            "syria": "سوريا",
            "taiwan": "تايوان",
            "thailand": "تايلاند",
            "tunisia": "تونس",
            "uae": "الإمارات",
            "ukraine": "أوكرانيا",
            "united arab emirates": "الإمارات",
            "united states of america": "الولايات المتحدة",
            "vietnam": "فيتنام",
            "yemen": "اليمن",
        }